alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.ai_analyses;
alter publication supabase_realtime add table public.appointments;
alter publication supabase_realtime add table public.patients;
alter publication supabase_realtime add table public.knee_data_records;
alter publication supabase_realtime add table public.nursing_records;
alter publication supabase_realtime add table public.alert_logs;
alter publication supabase_realtime add table public.devices;
alter publication supabase_realtime add table public.device_bindings;
alter publication supabase_realtime add table public.sensor_sessions;
alter publication supabase_realtime add table public.sensor_samples;
alter publication supabase_realtime add table public.calibration_records;

alter table public.profiles enable row level security;
alter table public.ai_analyses enable row level security;
alter table public.appointments enable row level security;
alter table public.patients enable row level security;
alter table public.knee_data_records enable row level security;
alter table public.nursing_records enable row level security;
alter table public.alert_logs enable row level security;
alter table public.devices enable row level security;
alter table public.device_bindings enable row level security;
alter table public.sensor_sessions enable row level security;
alter table public.sensor_samples enable row level security;
alter table public.calibration_records enable row level security;

create policy "anon read profiles" on public.profiles for select using (true);
create policy "anon insert profiles" on public.profiles for insert with check (true);
create policy "anon update profiles" on public.profiles for update using (true) with check (true);
create policy "anon read ai analyses" on public.ai_analyses for select using (true);
create policy "anon insert ai analyses" on public.ai_analyses for insert with check (true);
create policy "anon read appointments" on public.appointments for select using (true);
create policy "anon insert appointments" on public.appointments for insert with check (true);
create policy "anon update appointments" on public.appointments for update using (true) with check (true);
create policy "anon read patients" on public.patients for select using (true);
create policy "anon read knee data" on public.knee_data_records for select using (true);
create policy "anon insert knee data" on public.knee_data_records for insert with check (true);
create policy "anon read nursing records" on public.nursing_records for select using (true);
create policy "anon insert nursing records" on public.nursing_records for insert with check (true);
create policy "anon read alerts" on public.alert_logs for select using (true);
create policy "anon update alerts" on public.alert_logs for update using (true) with check (true);
create policy "anon read devices" on public.devices for select using (true);
create policy "anon insert devices" on public.devices for insert with check (true);
create policy "anon update devices" on public.devices for update using (true) with check (true);
create policy "anon read device bindings" on public.device_bindings for select using (true);
create policy "anon insert device bindings" on public.device_bindings for insert with check (true);
create policy "anon update device bindings" on public.device_bindings for update using (true) with check (true);
create policy "anon read sensor sessions" on public.sensor_sessions for select using (true);
create policy "anon insert sensor sessions" on public.sensor_sessions for insert with check (true);
create policy "anon update sensor sessions" on public.sensor_sessions for update using (true) with check (true);
create policy "anon read sensor samples" on public.sensor_samples for select using (true);
create policy "anon insert sensor samples" on public.sensor_samples for insert with check (true);
create policy "anon read calibration records" on public.calibration_records for select using (true);
create policy "anon insert calibration records" on public.calibration_records for insert with check (true);
